### ISSUE TITLE
WebAssembly research

### ISSUE THREAD

**Issue by heyajulia** [heyajulia/energieprijzen#22]
I was researching WebAssembly to hopefully be able to run the bot on
[Cloudflare Workers](https://workers.cloudflare.com/). However, sadly I never even got to the point where I could run it
anywhere (and I'm not blaming anyone but myself). This document serves as a log of my journey.

## Installing `wasmtime` and building the bot for WebAssembly is a piece of cake...

```bash
curl https://wasmtime.dev/install.sh -sSf | bash
GOOS=wasip1 GOARCH=wasm go build -o main.wasm cmd/bot/main.go
```

## ...but running it is a different story

```bash
wasmtime --env ENERGIEPRIJZEN_BOT_TOKEN=somevalue --env ENERGIEPRIJZEN_BOT_CHAT_ID=somevalue main.wasm
```

```
2023/11/11 14:35:58 main.go:52: Get "https://api.energyzero.nl/v1/energyprices?fromDate=2023-11-11T22%3A00%3A00Z&inclBtw=true&interval=4&tillDate=2023-11-12T21%3A59%3A59.999Z&usageType=1": dial tcp: lookup api.energyzero.nl on [::1]:53: dial udp [::1]:53: Connection refused
```

## Side-stepping the DNS issue

Hard-coding the/an IP address also doesn't work:

<details>
<summary>Minimal reproducible example</summary>

```go
package main

import (
	"fmt"
	"io"
	"net/http"
)

func main() {
	const ip = `93.184.216.34` // example.com

	req, err := http.NewRequest("GET", "http://"+ip, nil)
	if err != nil {
		panic(err)
	}
	req.Host = "example.com"

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	b, err := io.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(b))
}
```

</details>

```
panic: Get "http://93.184.216.34": dial tcp 93.184.216.34:80: Connection refused

goroutine 1 [running]:
main.main()
        /workspaces/energieprijzen/main.go:20 +0x2e
```

## `stealthrocket/net` to the rescue?

There's [`stealthrocket/net`](http://go/gh/stealthrocket/net), which is mentioned in a
[post on the Go blog](https://go.dev/blog/wasi), but it doesn't seem to work for my use case:

```go
import (
	// everything is the same as in the minimal reproducible example, except I've added this import:
	_ "github.com/stealthrocket/net/http"
)
```

```
Error: failed to run main module `main.wasm`

Caused by:
    0: failed to instantiate "main.wasm"
    1: unknown import: `wasi_snapshot_preview1::sock_open` has not been defined
```

## The future is looking bright

My WebAssembly adventure ends here for now, but the future is looking bright. I found
[the WASI HTTP proposal](http://go/gh/WebAssembly/wasi-http), which is currently in phase 2 of 5. Fingers crossed!

**Comment by heyajulia** [comment]
Maybe... I could compile the bot to JS and run it that way? This modified MRE works completely fine in [the GopherJS playground](https://gopherjs.github.io/playground/#/UzCAATjTBX):

```go
package main

import (
	"fmt"
	"io"
	"net/http"
)

func main() {
	// 🚨 SECURITY: This is just to make it work in the GopherJS playground. Don't do this in prod.
	req, err := http.NewRequest("GET", "https://corsproxy.io?https://example.com", nil)
	if err != nil {
		panic(err)
	}

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	b, err := io.ReadAll(resp.Body)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(b))
}
```
